spring:
  application:
    name: order-service
#  config:
#    import: optional:configserver:http://localhost:8080

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/order_service
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

exchange:
  one: https://exchange.matraining.com/7d21b2cb-9942-4948-9699-1b9fa5a8ad1c
  two: https://exchange2.matraining.com/7d21b2cb-9942-4948-9699-1b9fa5a8ad1c

#server:
#  port: 9090
